### ISSUE TITLE
Crash when clicking on Alerts button

### ISSUE THREAD

**Issue by pilhuhn** [hawkular/hawkular-android-client#14]
I think I don't have any alerts yet in the system.

```
E/AndroidRuntime(30580): Process: org.hawkular.client.android, PID: 30580
E/AndroidRuntime(30580): java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List org.hawkular.client.android.backend.model.Alert.getEvaluations()' on a null object reference
E/AndroidRuntime(30580):    at org.hawkular.client.android.adapter.AlertsAdapter.getAlertStartTimestamp(AlertsAdapter.java:157)
E/AndroidRuntime(30580):    at org.hawkular.client.android.adapter.AlertsAdapter.getAlertTitle(AlertsAdapter.java:95)
E/AndroidRuntime(30580):    at org.hawkular.client.android.adapter.AlertsAdapter.bindView(AlertsAdapter.java:90)
E/AndroidRuntime(30580):    at org.hawkular.client.android.adapter.AlertsAdapter.bindView(AlertsAdapter.java:40)
E/AndroidRuntime(30580):    at org.hawkular.client.android.adapter.BindableAdapter.getView(BindableAdapter.java:42)
E/AndroidRuntime(30580):    at android.widget.AbsListView.obtainView(AbsListView.java:2346)
E/AndroidRuntime(30580):    at android.widget.ListView.makeAndAddView(ListView.java:1864)
```

**Comment by arturdryomov** [comment]
Yep, seems like it. I actually thought AeroGear will return an empty list in such cases.

**Comment by arturdryomov** [comment]
- https://issues.jboss.org/browse/AGDROID-426
- https://issues.jboss.org/browse/HWKALERTS-59

**Comment by danielpassos** [comment]
I'm working on it https://github.com/aerogear/aerogear-android-pipe/pull/36

**Comment by arturdryomov** [comment]
Put a workaround at the #25 before the Pipe 2.2.0 is released.

**Comment by danielpassos** [comment]
AeroGear Android Pipe 2.2.1 staged

http://aerogear-dev.1069024.n5.nabble.com/aerogear-dev-AeroGear-Android-Pipe-2-1-1-td11862.html

**Comment by arturdryomov** [comment]
Was fixed for a while.
