### ISSUE TITLE
App crashes on adding a metric to favourite

### ISSUE THREAD

**Issue by pg301** [hawkular/hawkular-android-client#186]
`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.hawkular.client.android, PID: 2860
                  java.lang.IllegalStateException: Required view 'button_menu' with ID 2131624118 for field 'menuButton' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.
                      at butterknife.internal.Utils.findRequiredView(Utils.java:92)
                      at org.hawkular.client.android.adapter.FavMetricsAdapter$ViewHolder_ViewBinding.<init>(FavMetricsAdapter$ViewHolder_ViewBinding.java:24)
                      at java.lang.reflect.Constructor.newInstance0(Native Method)
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                      at butterknife.ButterKnife.createBinding(ButterKnife.java:199)
                      at butterknife.ButterKnife.bind(ButterKnife.java:172)
                      at org.hawkular.client.android.adapter.FavMetricsAdapter$ViewHolder.<init>(FavMetricsAdapter.java:118)
                      at org.hawkular.client.android.adapter.FavMetricsAdapter.newView(FavMetricsAdapter.java:79)
                      at org.hawkular.client.android.adapter.BindableAdapter.getView(BindableAdapter.java:45)
                      at android.widget.AbsListView.obtainView(AbsListView.java:2363)
                      at android.widget.ListView.makeAndAddView(ListView.java:1970)
                      at android.widget.ListView.fillDown(ListView.java:704)
                      at android.widget.ListView.fillFromTop(ListView.java:765)
                      at android.widget.ListView.layoutChildren(ListView.java:1716)
                      at android.widget.AbsListView.onLayout(AbsListView.java:2162)
                      at android.view.View.layout(View.java:17637)
                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                      at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:636)
                      at android.view.View.layout(View.java:17637)
                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                      at android.view.View.layout(View.java:17637)
                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                      at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
                      at android.view.View.layout(View.java:17637)
                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                      at android.view.View.layout(View.java:17637)
                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                      at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
                      at android.view.View.layout(View.java:17637)
                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                      at android.view.View.layout(View.java:17637)
                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                      at android.view.View.layout(View.java:17637)
                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                      at android.view.View.layout(View.java:17637)
                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                      at android.view.View.layout(View.java:17637)
                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                      at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
                      at android.view.View.layout(View.java:17637)
                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
E/AndroidRuntime:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                      at android.view.Choreographer.doFrame(Choreographer.java:621)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

`

![crash](https://cloud.githubusercontent.com/assets/10026907/24198024/172f0ace-0f2a-11e7-9fd5-824d40f91b8c.gif)

**Comment by pg301** [comment]
https://paste.ubuntu.com/24228237/ 

Here's the paste bin link

**Comment by anant-dev** [comment]
@garg-anuj What is the layout for the fav metric  :
do we need to put image button as in layout_list_item_alert 
or a toggle button as in  layout_list_item_token 
**This issue** is only because of different id in the layout referred so please clarify the ui (as the app crash only because image view is referred in a layout containing toggle button)
![screenshot_2017-03-22-22-46-49-904](https://cloud.githubusercontent.com/assets/13196029/24211460/21d5373c-0f52-11e7-90ba-92e898bbc874.jpeg)
