### ISSUE TITLE
Crash when server is not reachable

### ISSUE THREAD

**Issue by pilhuhn** [hawkular/hawkular-android-client#23]
```
E/HttpRestProvider(  919): Error on POST of http://209.132.179.82:18080/auth/realms/hawkular/tokens/refresh
E/HttpRestProvider(  919): java.net.ConnectException: failed to connect to /209.132.179.82 (port 18080): connect failed: ECONNREFUSED (Connection refused)
E/HttpRestProvider(  919):  at libcore.io.IoBridge.connect(IoBridge.java:124)
E/HttpRestProvider(  919):  at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
E/HttpRestProvider(  919):  at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
E/HttpRestProvider(  919):  at java.net.Socket.connect(Socket.java:882)
E/HttpRestProvider(  919):  at com.android.okhttp.internal.Platform.connectSocket(Platform.java:139)
E/HttpRestProvider(  919):  at com.android.okhttp.Connection.connect(Connection.java:148)
E/HttpRestProvider(  919):  at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
E/HttpRestProvider(  919):  at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
E/HttpRestProvider(  919):  at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
E/HttpRestProvider(  919):  at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
E/HttpRestProvider(  919):  at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:208)
E/HttpRestProvider(  919):  at org.jboss.aerogear.android.pipe.http.HttpRestProvider.addBodyRequest(HttpRestProvider.java:220)
E/HttpRestProvider(  919):  at org.jboss.aerogear.android.pipe.http.HttpRestProvider.post(HttpRestProvider.java:148)
E/HttpRestProvider(  919):  at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.runAccountAction(OAuth2AuthzService.java:259)
E/HttpRestProvider(  919):  at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.refreshAccount(OAuth2AuthzService.java:232)
E/HttpRestProvider(  919):  at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.fetchAccessToken(OAuth2AuthzService.java:88)
E/HttpRestProvider(  919):  at org.jboss.aerogear.android.authorization.oauth2.OAuth2FetchAccess$1.doInBackground(OAuth2FetchAccess.java:51)
E/HttpRestProvider(  919):  at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/HttpRestProvider(  919):  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/HttpRestProvider(  919):  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/HttpRestProvider(  919):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/HttpRestProvider(  919):  at java.lang.Thread.run(Thread.java:818)
E/HttpRestProvider(  919): Caused by: android.system.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
E/HttpRestProvider(  919):  at libcore.io.Posix.connect(Native Method)
E/HttpRestProvider(  919):  at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)
E/HttpRestProvider(  919):  at libcore.io.IoBridge.connectErrno(IoBridge.java:137)
E/HttpRestProvider(  919):  at libcore.io.IoBridge.connect(IoBridge.java:122)
E/HttpRestProvider(  919):  ... 21 more
E/AndroidRuntime(  919): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime(  919): Process: org.hawkular.client.android, PID: 919
E/AndroidRuntime(  919): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(  919):    at android.os.AsyncTask$3.done(AsyncTask.java:300)
E/AndroidRuntime(  919):    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime(  919):    at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime(  919):    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(  919):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(  919):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(  919):    at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime(  919): Caused by: java.lang.RuntimeException: java.net.ConnectException: failed to connect to /209.132.179.82 (port 18080): connect failed: ECONNREFUSED (Connection refused)
E/AndroidRuntime(  919):    at org.jboss.aerogear.android.pipe.http.HttpRestProvider.post(HttpRestProvider.java:153)
E/AndroidRuntime(  919):    at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.runAccountAction(OAuth2AuthzService.java:259)
E/AndroidRuntime(  919):    at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.refreshAccount(OAuth2AuthzService.java:232)
E/AndroidRuntime(  919):    at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.fetchAccessToken(OAuth2AuthzService.java:88)
E/AndroidRuntime(  919):    at org.jboss.aerogear.android.authorization.oauth2.OAuth2FetchAccess$1.doInBackground(OAuth2FetchAccess.java:51)
E/AndroidRuntime(  919):    at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/AndroidRuntime(  919):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(  919):    ... 3 more
E/AndroidRuntime(  919): Caused by: java.net.ConnectException: failed to connect to /209.132.179.82 (port 18080): connect failed: ECONNREFUSED (Connection refused)
E/AndroidRuntime(  919):    at libcore.io.IoBridge.connect(IoBridge.java:124)
E/AndroidRuntime(  919):    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
E/AndroidRuntime(  919):    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
E/AndroidRuntime(  919):    at java.net.Socket.connect(Socket.java:882)
E/AndroidRuntime(  919):    at com.android.okhttp.internal.Platform.connectSocket(Platform.java:139)
E/AndroidRuntime(  919):    at com.android.okhttp.Connection.connect(Connection.java:148)
E/AndroidRuntime(  919):    at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
E/AndroidRuntime(  919):    at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
E/AndroidRuntime(  919):    at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
E/AndroidRuntime(  919):    at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
E/AndroidRuntime(  919):    at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:208)
E/AndroidRuntime(  919):    at org.jboss.aerogear.android.pipe.http.HttpRestProvider.addBodyRequest(HttpRestProvider.java:220)
E/AndroidRuntime(  919):    at org.jboss.aerogear.android.pipe.http.HttpRestProvider.post(HttpRestProvider.java:148)
E/AndroidRuntime(  919):    ... 9 more
E/AndroidRuntime(  919): Caused by: android.system.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
E/AndroidRuntime(  919):    at libcore.io.Posix.connect(Native Method)
E/AndroidRuntime(  919):    at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)
E/AndroidRuntime(  919):    at libcore.io.IoBridge.connectErrno(IoBridge.java:137)
E/AndroidRuntime(  919):    at libcore.io.IoBridge.connect(IoBridge.java:122)
E/AndroidRuntime(  919):    ... 21 more
W/ActivityManager(  773):   Force finishing activity org.hawkular.client.android/.activity.AuthorizationActivity
W/ResourceType(  773): For resource 0x010301f2, entry index(498) is beyond type entryCount(9)
E/ActivityManager(  773): Invalid thumbnail dimensions: 576x576
D/LogFetchServiceManager(24705): Received entry added
I/OpenGLRenderer(  773): Initialized EGL, version 1.4
I/Timeline( 2134): Timeline: Activity_idle id: android.os.BinderProxy@3bcc7d40 time:1248983421
D/OpenGLRenderer(  919): endAllStagingAnimators on 0xaf2e0b80 (RippleDrawable) with handle 0xacd07b10
I/Timeline(  773): Timeline: Activity_windows_visible id: ActivityRecord{1f53169d u0 com.cyanogenmod.trebuchet/com.android.launcher3.Launcher t618} time:1248983688
I/ActivityManager(  773): Killing 354:com.android.keychain/1000 (adj 15): empty #17
W/libprocessgroup(  773): failed to open /acct/uid_1000/pid_354/cgroup.procs: No such file or directory
E/ActivityThread(  919): Activity org.hawkular.client.android.activity.AuthorizationActivity has leaked ServiceConnection org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzModule$1@357b434b that was originally bound here
E/ActivityThread(  919): android.app.ServiceConnectionLeaked: Activity org.hawkular.client.android.activity.AuthorizationActivity has leaked ServiceConnection org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzModule$1@357b434b that was originally bound here
E/ActivityThread(  919):    at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1073)
E/ActivityThread(  919):    at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:967)
E/ActivityThread(  919):    at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1802)
E/ActivityThread(  919):    at android.app.ContextImpl.bindService(ContextImpl.java:1785)
E/ActivityThread(  919):    at android.content.ContextWrapper.bindService(ContextWrapper.java:544)
E/ActivityThread(  919):    at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzModule.requestAccess(OAuth2AuthzModule.java:104)
E/ActivityThread(  919):    at org.hawkular.client.android.backend.BackendClient.authorize(BackendClient.java:106)
E/ActivityThread(  919):    at org.hawkular.client.android.activity.AuthorizationActivity.setUpBackendAuthorization(AuthorizationActivity.java:131)
E/ActivityThread(  919):    at org.hawkular.client.android.activity.AuthorizationActivity.setUpAuthorization(AuthorizationActivity.java:99)
E/ActivityThread(  919):    at org.hawkular.client.android.activity.AuthorizationActivity$$ViewInjector$1.doClick(AuthorizationActivity$$ViewInjector.java:23)
E/ActivityThread(  919):    at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
E/ActivityThread(  919):    at android.view.View.performClick(View.java:4756)
E/ActivityThread(  919):    at android.view.View$PerformClick.run(View.java:19748)
E/ActivityThread(  919):    at android.os.Handler.handleCallback(Handler.java:739)
E/ActivityThread(  919):    at android.os.Handler.dispatchMessage(Handler.java:95)
E/ActivityThread(  919):    at android.os.Looper.loop(Looper.java:135)
E/ActivityThread(  919):    at android.app.ActivityThread.main(ActivityThread.java:5254)
E/ActivityThread(  919):    at java.lang.reflect.Method.invoke(Native Method)
E/ActivityThread(  919):    at java.lang.reflect.Method.invoke(Method.java:372)
E/ActivityThread(  919):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
E/ActivityThread(  919):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
E/StrictMode(  919): null
E/StrictMode(  919): android.app.ServiceConnectionLeaked: Activity org.hawkular.client.android.activity.AuthorizationActivity has leaked ServiceConnection org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzModule$1@357b434b that was originally bound here
E/StrictMode(  919):    at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1073)
E/StrictMode(  919):    at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:967)
E/StrictMode(  919):    at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1802)
E/StrictMode(  919):    at android.app.ContextImpl.bindService(ContextImpl.java:1785)
E/StrictMode(  919):    at android.content.ContextWrapper.bindService(ContextWrapper.java:544)
E/StrictMode(  919):    at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzModule.requestAccess(OAuth2AuthzModule.java:104)
E/StrictMode(  919):    at org.hawkular.client.android.backend.BackendClient.authorize(BackendClient.java:106)
E/StrictMode(  919):    at org.hawkular.client.android.activity.AuthorizationActivity.setUpBackendAuthorization(AuthorizationActivity.java:131)
E/StrictMode(  919):    at org.hawkular.client.android.activity.AuthorizationActivity.setUpAuthorization(AuthorizationActivity.java:99)
E/StrictMode(  919):    at org.hawkular.client.android.activity.AuthorizationActivity$$ViewInjector$1.doClick(AuthorizationActivity$$ViewInjector.java:23)
E/StrictMode(  919):    at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
E/StrictMode(  919):    at android.view.View.performClick(View.java:4756)
E/StrictMode(  919):    at android.view.View$PerformClick.run(View.java:19748)
E/StrictMode(  919):    at android.os.Handler.handleCallback(Handler.java:739)
E/StrictMode(  919):    at android.os.Handler.dispatchMessage(Handler.java:95)
E/StrictMode(  919):    at android.os.Looper.loop(Looper.java:135)
E/StrictMode(  919):    at android.app.ActivityThread.main(ActivityThread.java:5254)
E/StrictMode(  919):    at java.lang.reflect.Method.invoke(Native Method)
E/StrictMode(  919):    at java.lang.reflect.Method.invoke(Method.java:372)
E/StrictMode(  919):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
E/StrictMode(  919):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
W/ActivityManager(  773): Unbind failed: could not find connection for android.os.BinderProxy@3fe2a7a6
W/SurfaceFlinger(  233): couldn't log to binary event log: overflow.
```

**Comment by arturdryomov** [comment]
Does it happen in the process of the authorization? For me if a server is unreachable after pressing the “Authorize” button AeroGear just updates the dialog with the “Webpage not available” status.

**Comment by arturdryomov** [comment]
OS version is CyanogenMod 5.0.2. At the same time AOSP 5.1.1 works fine and just shows the error-related webpage.

**Comment by arturdryomov** [comment]
Just checked the emulator with AOSP 5.1.1 — works just fine. @danielpassos Can you please take a look at this?

**Comment by ming13** [comment]
![animation](https://cloud.githubusercontent.com/assets/200401/8425019/3d06b16e-1f0a-11e5-9892-eec8dcacc21d.gif)

**Comment by danielpassos** [comment]
```
06-30 07:55:56.987    9512-9593/org.hawkular.client.android E/HttpRestProvider﹕ Error on POST of http://209.132.179.82:18080/auth/realms/hawkular/tokens/refresh
    java.net.ConnectException: failed to connect to /209.132.179.82 (port 18080): connect failed: ECONNREFUSED (Connection refused)
            at libcore.io.IoBridge.connect(IoBridge.java:124)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
            at java.net.Socket.connect(Socket.java:882)
            at com.android.okhttp.internal.Platform.connectSocket(Platform.java:139)
            at com.android.okhttp.Connection.connect(Connection.java:148)
            at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
            at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:208)
            at org.jboss.aerogear.android.pipe.http.HttpRestProvider.addBodyRequest(HttpRestProvider.java:220)
            at org.jboss.aerogear.android.pipe.http.HttpRestProvider.post(HttpRestProvider.java:148)
            at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.runAccountAction(OAuth2AuthzService.java:259)
            at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.refreshAccount(OAuth2AuthzService.java:232)
            at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.fetchAccessToken(OAuth2AuthzService.java:88)
            at org.jboss.aerogear.android.authorization.oauth2.OAuth2FetchAccess$1.doInBackground(OAuth2FetchAccess.java:51)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: android.system.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
            at libcore.io.Posix.connect(Native Method)
            at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)
            at libcore.io.IoBridge.connectErrno(IoBridge.java:137)
            at libcore.io.IoBridge.connect(IoBridge.java:122)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
            at java.net.Socket.connect(Socket.java:882)
            at com.android.okhttp.internal.Platform.connectSocket(Platform.java:139)
            at com.android.okhttp.Connection.connect(Connection.java:148)
            at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
            at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:208)
            at org.jboss.aerogear.android.pipe.http.HttpRestProvider.addBodyRequest(HttpRestProvider.java:220)
            at org.jboss.aerogear.android.pipe.http.HttpRestProvider.post(HttpRestProvider.java:148)
            at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.runAccountAction(OAuth2AuthzService.java:259)
            at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.refreshAccount(OAuth2AuthzService.java:232)
            at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.fetchAccessToken(OAuth2AuthzService.java:88)
            at org.jboss.aerogear.android.authorization.oauth2.OAuth2FetchAccess$1.doInBackground(OAuth2FetchAccess.java:51)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
06-30 07:55:56.988    9512-9593/org.hawkular.client.android E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #2
    Process: org.hawkular.client.android, PID: 9512
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:300)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.RuntimeException: java.net.ConnectException: failed to connect to /209.132.179.82 (port 18080): connect failed: ECONNREFUSED (Connection refused)
            at org.jboss.aerogear.android.pipe.http.HttpRestProvider.post(HttpRestProvider.java:153)
            at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.runAccountAction(OAuth2AuthzService.java:259)
            at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.refreshAccount(OAuth2AuthzService.java:232)
            at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.fetchAccessToken(OAuth2AuthzService.java:88)
            at org.jboss.aerogear.android.authorization.oauth2.OAuth2FetchAccess$1.doInBackground(OAuth2FetchAccess.java:51)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.net.ConnectException: failed to connect to /209.132.179.82 (port 18080): connect failed: ECONNREFUSED (Connection refused)
            at libcore.io.IoBridge.connect(IoBridge.java:124)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
            at java.net.Socket.connect(Socket.java:882)
            at com.android.okhttp.internal.Platform.connectSocket(Platform.java:139)
            at com.android.okhttp.Connection.connect(Connection.java:148)
            at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
            at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:208)
            at org.jboss.aerogear.android.pipe.http.HttpRestProvider.addBodyRequest(HttpRestProvider.java:220)
            at org.jboss.aerogear.android.pipe.http.HttpRestProvider.post(HttpRestProvider.java:148)
            at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.runAccountAction(OAuth2AuthzService.java:259)
            at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.refreshAccount(OAuth2AuthzService.java:232)
            at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.fetchAccessToken(OAuth2AuthzService.java:88)
            at org.jboss.aerogear.android.authorization.oauth2.OAuth2FetchAccess$1.doInBackground(OAuth2FetchAccess.java:51)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: android.system.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
            at libcore.io.Posix.connect(Native Method)
            at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)
            at libcore.io.IoBridge.connectErrno(IoBridge.java:137)
            at libcore.io.IoBridge.connect(IoBridge.java:122)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
            at java.net.Socket.connect(Socket.java:882)
            at com.android.okhttp.internal.Platform.connectSocket(Platform.java:139)
            at com.android.okhttp.Connection.connect(Connection.java:148)
            at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
            at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:208)
            at org.jboss.aerogear.android.pipe.http.HttpRestProvider.addBodyRequest(HttpRestProvider.java:220)
            at org.jboss.aerogear.android.pipe.http.HttpRestProvider.post(HttpRestProvider.java:148)
            at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.runAccountAction(OAuth2AuthzService.java:259)
            at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.refreshAccount(OAuth2AuthzService.java:232)
            at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.fetchAccessToken(OAuth2AuthzService.java:88)
            at org.jboss.aerogear.android.authorization.oauth2.OAuth2FetchAccess$1.doInBackground(OAuth2FetchAccess.java:51)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
06-30 07:55:57.965    9512-9512/org.hawkular.client.android E/ActivityThread﹕ Activity org.hawkular.client.android.activity.AuthorizationActivity has leaked ServiceConnection org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzModule$1@2e8ef2e3 that was originally bound here
    android.app.ServiceConnectionLeaked: Activity org.hawkular.client.android.activity.AuthorizationActivity has leaked ServiceConnection org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzModule$1@2e8ef2e3 that was originally bound here
            at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1072)
            at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:966)
            at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1776)
            at android.app.ContextImpl.bindService(ContextImpl.java:1759)
            at android.content.ContextWrapper.bindService(ContextWrapper.java:538)
            at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzModule.requestAccess(OAuth2AuthzModule.java:104)
            at org.hawkular.client.android.backend.BackendClient.authorize(BackendClient.java:106)
            at org.hawkular.client.android.activity.AuthorizationActivity.setUpBackendAuthorization(AuthorizationActivity.java:131)
            at org.hawkular.client.android.activity.AuthorizationActivity.setUpAuthorization(AuthorizationActivity.java:99)
            at org.hawkular.client.android.activity.AuthorizationActivity$$ViewBinder$1.doClick(AuthorizationActivity$$ViewBinder.java:23)
            at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
            at android.view.View.performClick(View.java:4756)
            at android.view.View$PerformClick.run(View.java:19749)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
06-30 07:55:57.965    9512-9512/org.hawkular.client.android E/StrictMode﹕ null
    android.app.ServiceConnectionLeaked: Activity org.hawkular.client.android.activity.AuthorizationActivity has leaked ServiceConnection org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzModule$1@2e8ef2e3 that was originally bound here
            at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1072)
            at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:966)
            at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1776)
            at android.app.ContextImpl.bindService(ContextImpl.java:1759)
            at android.content.ContextWrapper.bindService(ContextWrapper.java:538)
            at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzModule.requestAccess(OAuth2AuthzModule.java:104)
            at org.hawkular.client.android.backend.BackendClient.authorize(BackendClient.java:106)
            at org.hawkular.client.android.activity.AuthorizationActivity.setUpBackendAuthorization(AuthorizationActivity.java:131)
            at org.hawkular.client.android.activity.AuthorizationActivity.setUpAuthorization(AuthorizationActivity.java:99)
            at org.hawkular.client.android.activity.AuthorizationActivity$$ViewBinder$1.doClick(AuthorizationActivity$$ViewBinder.java:23)
            at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
            at android.view.View.performClick(View.java:4756)
            at android.view.View$PerformClick.run(View.java:19749)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
06-30 07:56:26.748    9512-9512/org.hawkular.client.android D/PushClient﹕ Push registration failed.
    org.jboss.aerogear.android.pipe.http.HttpException: The server returned the error code 503.
            at org.jboss.aerogear.android.pipe.http.HttpRestProvider.getHeaderAndBody(HttpRestProvider.java:288)
            at org.jboss.aerogear.android.pipe.http.HttpRestProvider.post(HttpRestProvider.java:149)
            at org.jboss.aerogear.android.pipe.http.HttpRestProvider.post(HttpRestProvider.java:135)
            at org.jboss.aerogear.android.unifiedpush.gcm.AeroGearGCMPushRegistrar$3.doInBackground(AeroGearGCMPushRegistrar.java:158)
            at org.jboss.aerogear.android.unifiedpush.gcm.AeroGearGCMPushRegistrar$3.doInBackground(AeroGearGCMPushRegistrar.java:120)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

**Comment by openwarrior** [comment]
@danielpassos This issue no longer exist
