### ISSUE TITLE
App terminates when remote host is not reachable (with pr36)

### ISSUE THREAD

**Issue by pilhuhn** [hawkular/hawkular-android-client#37]
I have from a previous run a server in my app cache, that is currently not up/reachable.
The app (with PR #36  applied) just quits and a box "Hawkular was terminated. OK" system popup
shows.
Another similar crash wrt the demo.hawkular.org instance is below 

The app should catch that and offer to potentially switch to a different server.

Note that after clearing the cache the situation improved, so this issue may be void

```
E/HttpRestProvider(13467): Error on POST of http://172.31.7.7:8080/auth/realms/hawkular/tokens/refresh
E/HttpRestProvider(13467): java.net.ConnectException: failed to connect to /172.31.7.7 (port 8080): connect failed: EHOSTUNREACH (No route to host)
E/HttpRestProvider(13467):  at libcore.io.IoBridge.connect(IoBridge.java:124)
E/HttpRestProvider(13467):  at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
E/HttpRestProvider(13467):  at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
E/HttpRestProvider(13467):  at java.net.Socket.connect(Socket.java:882)
E/HttpRestProvider(13467):  at com.android.okhttp.internal.Platform.connectSocket(Platform.java:139)
E/HttpRestProvider(13467):  at com.android.okhttp.Connection.connect(Connection.java:148)
E/HttpRestProvider(13467):  at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
E/HttpRestProvider(13467):  at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
E/HttpRestProvider(13467):  at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
E/HttpRestProvider(13467):  at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
E/HttpRestProvider(13467):  at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:208)
E/HttpRestProvider(13467):  at org.jboss.aerogear.android.pipe.http.HttpRestProvider.addBodyRequest(HttpRestProvider.java:220)
E/HttpRestProvider(13467):  at org.jboss.aerogear.android.pipe.http.HttpRestProvider.post(HttpRestProvider.java:148)
E/HttpRestProvider(13467):  at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.runAccountAction(OAuth2AuthzService.java:259)
E/HttpRestProvider(13467):  at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.refreshAccount(OAuth2AuthzService.java:232)
E/HttpRestProvider(13467):  at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.fetchAccessToken(OAuth2AuthzService.java:88)
E/HttpRestProvider(13467):  at org.jboss.aerogear.android.authorization.oauth2.OAuth2FetchAccess$1.doInBackground(OAuth2FetchAccess.java:51)
E/HttpRestProvider(13467):  at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/HttpRestProvider(13467):  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/HttpRestProvider(13467):  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/HttpRestProvider(13467):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/HttpRestProvider(13467):  at java.lang.Thread.run(Thread.java:818)
E/HttpRestProvider(13467): Caused by: android.system.ErrnoException: connect failed: EHOSTUNREACH (No route to host)
E/HttpRestProvider(13467):  at libcore.io.Posix.connect(Native Method)
E/HttpRestProvider(13467):  at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)
E/HttpRestProvider(13467):  at libcore.io.IoBridge.connectErrno(IoBridge.java:137)
E/HttpRestProvider(13467):  at libcore.io.IoBridge.connect(IoBridge.java:122)
E/HttpRestProvider(13467):  ... 21 more
E/AndroidRuntime(13467): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime(13467): Process: org.hawkular.client.android, PID: 13467
E/AndroidRuntime(13467): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(13467):    at android.os.AsyncTask$3.done(AsyncTask.java:300)
E/AndroidRuntime(13467):    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime(13467):    at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime(13467):    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(13467):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(13467):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(13467):    at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime(13467): Caused by: java.lang.RuntimeException: java.net.ConnectException: failed to connect to /172.31.7.7 (port 8080): connect failed: EHOSTUNREACH (No route to host)
E/AndroidRuntime(13467):    at org.jboss.aerogear.android.pipe.http.HttpRestProvider.post(HttpRestProvider.java:153)
E/AndroidRuntime(13467):    at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.runAccountAction(OAuth2AuthzService.java:259)
E/AndroidRuntime(13467):    at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.refreshAccount(OAuth2AuthzService.java:232)
E/AndroidRuntime(13467):    at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.fetchAccessToken(OAuth2AuthzService.java:88)
E/AndroidRuntime(13467):    at org.jboss.aerogear.android.authorization.oauth2.OAuth2FetchAccess$1.doInBackground(OAuth2FetchAccess.java:51)
E/AndroidRuntime(13467):    at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/AndroidRuntime(13467):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(13467):    ... 3 more
E/AndroidRuntime(13467): Caused by: java.net.ConnectException: failed to connect to /172.31.7.7 (port 8080): connect failed: EHOSTUNREACH (No route to host)
E/AndroidRuntime(13467):    at libcore.io.IoBridge.connect(IoBridge.java:124)
E/AndroidRuntime(13467):    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
E/AndroidRuntime(13467):    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
E/AndroidRuntime(13467):    at java.net.Socket.connect(Socket.java:882)
E/AndroidRuntime(13467):    at com.android.okhttp.internal.Platform.connectSocket(Platform.java:139)
E/AndroidRuntime(13467):    at com.android.okhttp.Connection.connect(Connection.java:148)
E/AndroidRuntime(13467):    at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
E/AndroidRuntime(13467):    at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
E/AndroidRuntime(13467):    at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
E/AndroidRuntime(13467):    at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
E/AndroidRuntime(13467):    at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:208)
E/AndroidRuntime(13467):    at org.jboss.aerogear.android.pipe.http.HttpRestProvider.addBodyRequest(HttpRestProvider.java:220)
E/AndroidRuntime(13467):    at org.jboss.aerogear.android.pipe.http.HttpRestProvider.post(HttpRestProvider.java:148)
E/AndroidRuntime(13467):    ... 9 more
E/AndroidRuntime(13467): Caused by: android.system.ErrnoException: connect failed: EHOSTUNREACH (No route to host)
E/AndroidRuntime(13467):    at libcore.io.Posix.connect(Native Method)
E/AndroidRuntime(13467):    at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)
E/AndroidRuntime(13467):    at libcore.io.IoBridge.connectErrno(IoBridge.java:137)
E/AndroidRuntime(13467):    at libcore.io.IoBridge.connect(IoBridge.java:122)
E/AndroidRuntime(13467):    ... 21 more
W/ActivityManager(  778):   Force finishing activity org.hawkular.client.android/.activity.DrawerActivity

```

```
E/AndroidRuntime(15702): FATAL EXCEPTION: AsyncTask #2
E/AndroidRuntime(15702): Process: org.hawkular.client.android, PID: 15702
E/AndroidRuntime(15702): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(15702):    at android.os.AsyncTask$3.done(AsyncTask.java:300)
E/AndroidRuntime(15702):    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime(15702):    at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime(15702):    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(15702):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(15702):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(15702):    at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime(15702): Caused by: org.jboss.aerogear.android.pipe.http.HttpException: The server returned the error code 502.
E/AndroidRuntime(15702):    at org.jboss.aerogear.android.pipe.http.HttpRestProvider.getHeaderAndBody(HttpRestProvider.java:288)
E/AndroidRuntime(15702):    at org.jboss.aerogear.android.pipe.http.HttpRestProvider.post(HttpRestProvider.java:149)
E/AndroidRuntime(15702):    at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.runAccountAction(OAuth2AuthzService.java:259)
E/AndroidRuntime(15702):    at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.refreshAccount(OAuth2AuthzService.java:232)
E/AndroidRuntime(15702):    at org.jboss.aerogear.android.authorization.oauth2.OAuth2AuthzService.fetchAccessToken(OAuth2AuthzService.java:88)
E/AndroidRuntime(15702):    at org.jboss.aerogear.android.authorization.oauth2.OAuth2FetchAccess$1.doInBackground(OAuth2FetchAccess.java:51)
E/AndroidRuntime(15702):    at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/AndroidRuntime(15702):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(15702):    ... 3 more
W/ActivityManager(  778):   Force finishing activity org.hawkular.client.android/.activity.AuthorizationActivity
```

**Comment by arturdryomov** [comment]
Seems like it tries to refresh the authorization token, but fails because the server is not available. I’ll try to reproduce.
